### ISSUE TITLE
ToDO

### ISSUE THREAD

**Issue by elena-krismer** [27410/27410-2020-group-project-group12-c-reinhardtii#2]
- [ ] which lipids? 16:0, 18:0,..omega,...

- [ ] create objective that includes all lipids (help from niko)

- [ ] removal reaction for lipids

- [ ] model testing
